name: "vzlogger"
description: "vzlogger addon for home assistant"
version: "0.1.0"
slug: "vzlogger"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8082/tcp: 8082
devices:
  - /dev/ttyUSB0
